export default {
  LOGO: require("../assets/images/logo.png"),
  ONBOARDINGBG: require("../assets/images/onboarding.png"),
  PATTERNBG: require("../assets/images/pattern.png"),
  PINLOGO: require("../assets/images/pin_logo.png"),
  DONEIMAGE: require("../assets/images/done.png"),
  BACKETIMAGE: require("../assets/images/backet.png"),
  NOTWIFI: require("../assets/images/not_wifi.png"),
  DISH_CAKE: require("../assets/images/dish_cake.png"),
  DISH_FISH: require("../assets/images/dish_fish.png"),
  DISH_FRUIT: require("../assets/images/dish_fruit.png"),
  DISH_LOW_FAT: require("../assets/images/dish_low_fat.png"),
  DISH_SPICY: require("../assets/images/dish_spicy.png"),
  DISH_VEGA: require("../assets/images/dish_vega.png"),
  DISH_VEGETABLE: require("../assets/images/dish_vegetable.png"),
  DISH_SALTY: require("../assets/images/dish_salty.png"),
  ICON_FOOD: require("../assets/images/icon_food.png"),
  ICON_FRUIT: require("../assets/images/icon_fruit.png"),
  ICON_OTHER: require("../assets/images/icon_other.png"),
  ICON_VEGETABLE: require("../assets/images/icon_vegetable.png"),
  ICON_WATER: require("../assets/images/icon_water.png"),
};
