export const commonFoods = [
  "Mì cay",
  "Mì",
  "hành lá",
  "tỏi",
  "lợn",
  "gà",
  "ớt",
  "đậu phụ",
  "mắm",
  "nước mắm",
  "rau",
  "rau thơm",
  "mù tạc",
  "bò",
  "heo",
  "gia cầm",
  "cừu",
  "dê",
  "cừu",
  "thỏ",
  "ngựa",
  "nai",
  "cừu",
  "gấu",
  "hươu",
  "cá sấu",
  "rắn",
  "chim",
  "đà điểu",
  "hải cẩu",
  "cá",
  "cá trích",
  "cá hồi",
  "cá ngừ",
  "cá trê",
  "cá basa",
  "cá trích",
  "cá chình",
  "cá thu",
  "cá hồi",
  "cá mập",
  "cá saba",
  "Hành tỏi",
  "Hành tây",
  "Hành lá",
  "Cà chua",
  "Ớt chuông",
  "Ớt hiểm",
  "Tiêu đen",
  "Tiêu xanh",
  "Ớt bột",
  "Gừng",
  "Lá quế",
  "Bạc hà",
  "Ngò rí",
  "Ngò gai",
  "Cà pháo",
  "Xả",
  "Hương thảo",
  "Rau mùi",
  "Rau húng",
  "Rau thơm",
  "Hành tỏi",
  "Hành tây",
  "Hành lá",
  "Cà chua",
  "Ớt chuông",
  "Ớt hiểm",
  "Tiêu đen",
  "Tiêu xanh",
  "Ớt bột",
  "Gừng",
  "Lá quế",
  "Bạc hà",
  "Ngò rí",
  "Ngò gai",
  "Cà pháo",
  "Xả",
  "Hương thảo",
  "Rau mùi",
  "Rau húng",
  "Rau thơm",
  "Mùi tàu",
  "Bông hẹ",
  "Mè",
  "Tỏi",
  "Gia vị nêm",
  "Muối",
  "Đường",
  "Bột ngọt",
  "Bột canh",
  "Bột ngọt hạt nêm",
  "Bột ngọt Maggi",
  "Bột ngọt Ajinomoto",
  "Bột ngọt Ve Tsin",
  "Bột ngọt Aji-ngon",
  "Bột ngọt Knorr",
  "Bột ngọt Umami",
  "Mì chính",
  "Hạt tiêu",
  "Bột ớt",
  "Tương ớt",
  "Tương cà",
  "Tương bột",
  "Bột nêm",
  "Bột nếp",
  "Bột nếp than",
  "Bột bành",
  "Bột sắn dây",
  "Bột mỳ",
  "Bột bắp",
  "Bột gạo",
  "Bột khoai mì",
  "Bột ngô",
  "Bột bí đỏ",
  "Bột năng",
  "Bột bắp chiên giòn",
  "Bột mỳ chiên giòn",
  "Bột chiên xù",
  "Bột trà xanh",
  "Bột mè",
  "Bột đậu nành",
  "Bột nui",
  "Bột gạo lức",
  "Bột sắn",
  "Bột đậu đỏ",
  "Bột trứng",
  "Bột khoai lang",
  "Bột củ dền",
  "Bột hạnh nhân",
  "Bột đậu xanh",
  "Bột lá dứa",
  "Bột nha đam",
  "Bột nghệ",
  "Bột lá dứa",
  "Bột dứa",
  "Bột nghệ",
  "Bột mắc ca",
  "Bột hạt sen",
  "Bột nước tắm",
  "Bột nghệ đen",
  "Bột nghệ vàng",
  "Bột rễ nghệ",
  "Bột gừng tươi",
  "Bột gừng khô",
  "Bột cúc đại",
  "Bột nước mắm",
  "Bột nước mắm tôm",
  "Bột nước mắm cá",
  "Bột mực",
  "Bột mắm tép",
  "Bột nấm",
  "Bột rong biển",
  "Bột hành",
  "Bột lá chanh",
  "Bột sả",
  "Bột vừng",
  "Bột ớt cay",
  "Bột ớt bằm",
  "Bột ớt sừng",
  "Bột ớt khô",
  "Bột ớt xay",
  "Bột nếp trắng",
  "Bột nếp than",
  "Bột nếp đen",
  "Bột nếp trái cây",
  "Bột nếp sắn",
  "Bột nếp nương",
  "Bột nếp cái hoa vàng",
  "Bột nếp đỗ xanh",
  "Bột nếp tím",
  "Bột nếp lá chuối",
  "Bột nếp lá dứa",
  "Bột nếp đen",
  "Bột nếp ngũ vị",
  "Bột nếp lá mít",
  "Bột nếp lá sen",
  "Bột nếp lá chuối",
  "Bột nếp lá dứa",
  "Bột nếp dừa",
  "Bột nếp mè",
  "Bột nếp lá gấm",
  "Đường",
  "Bột mì",
  "Bơ",
  "Trứng",
  "Sữa",
  "Sữa đặc",
  "Kem tươi",
  "Bột cacao",
  "Chocolate",
  "Bột bắp",
  "Nước cốt dừa",
  "Bột hạnh nhân",
  "Bột dừa",
  "Dừa tươi",
  "Sô-cô-la",
  "Nho khô",
  "Hạt dẻ",
  "Hạnh nhân",
  "Hạt điều",
  "Hạt lựu",
  "Hạt chia",
  "Hạt sen",
  "Hạt macadamia",
  "Hạt dưa hấu",
  "Hạt hướng dương",
  "Hạt bí",
  "Hạt óc chó",
  "Hạt quinoa",
  "Hạt flaxseed",
  "Hạt bí ngô",
  "Hạt lanh",
  "Hạt chân giò",
  "Hạt cải",
  "Hạt đậu",
  "Hạt đỗ",
  "Hạt đỗ xanh",
  "Hạt đậu đỏ",
  "Hạt nêm",
  "Hạt ngũ cốc",
  "Hạt nho",
  "Hạt phỉ",
  "Hạt phụ",
  "Hạt trái cây",
  "Hạt tiêu",
  "Hạt tiêu đen",
  "Hạt tiêu xanh",
  "Hạt tiêu hồng",
  "Hạt tiêu đỏ",
  "Hạt tiêu tím",
  "Hạt tiêu sọ",
  "Hạt tiêu sắc",
  "Hạt tiêu thái",
  "Táo",
  "Chuối",
  "Cam",
  "Nho",
  "Dưa hấu",
  "Dứa",
  "Cherry",
  "Kiwi",
  "Măng cụt",
  "Mận",
  "Dâu tây",
  "Lê",
  "Xoài",
  "Mít",
  "Lựu",
  "Đu đủ",
  "Ổi",
  "Quýt",
  "Bưởi",
  "Mận",
  "Việt quất",
  "Mâm xôi",
  "Đào",
  "Hồng xiêm",
  "Kiwi vàng",
  "Chanh dây",
  "Cây lê",
  "Cây táo",
  "Cây cam",
  "Cây chuối",
  "Cây măng cụt",
  "Cây dâu tây",
  "Cây kiwi",
  "Cây xoài",
  "Cây mít",
  "Cây lựu",
  "Cây đu đủ",
  "Cây ổi",
  "Cây quýt",
  "Cây bưởi",
  "Cây việt quất",
  "Cây mâm xôi",
  "Cây đào",
  "Cây hồng xiêm",
  "Dừa",
  "Mãng cầu",
  "Cà chua",
  "Mận",
  "Dưa gang",
  "Dưa leo",
  "Dứa",
  "Dừa xiêm",
  "Chuối xiêm",
  "Sầu riêng",
  "Dưa hấu",
  "Cam cao phong",
  "Dâu tây",
  "Táo mèo",
  "Ổi",
  "Mơ",
  "Hồng",
  "Chôm chôm",
  "Xoài cát",
  "Lê sơ ri",
  "Vú sữa",
  "Thanh long",
  "Lựu",
  "Dâu tằm",
  "Dứa xiêm xanh",
  "Dưa lưới",
  "Cóc",
  "Dưa hấu vàng",
  "Dưa gang lênh",
  "Dứa xiêm vàng",
  "Dưa hấu đỏ",
  "Kiwi vàng",
  "Mít tố nữ",
  "Mãng cầu xiêm",
  "Chanh leo",
  "Xoài xoài",
  "Mâm xôi",
  "Đu đủ vàng",
  "Ổi ruột đỏ",
  "Quýt khô",
  "Ổi ruột vàng",
  "Hồng xiêm ruột đỏ",
  "Cam sành",
  "Chanh dây ruột đỏ",
  "Ổi cát",
  "Sầu riêng",
  "Dưa hấu ruột đen",
  "Cam quýt",
  "Táo nhập khẩu",
  "Kiwi nhập khẩu",
  "Chuối nhập khẩu",
  "Dừa nhập khẩu",
  "Ổi nhập khẩu",
  "Quýt nhập khẩu",
  "Mận nhập khẩu",
  "Việt quất nhập khẩu",
  "Mâm xôi nhập khẩu",
  "Đào nhập khẩu",
  "Hồng xiêm nhập khẩu",
  "Chanh dây nhập khẩu",
  "Mít nhập khẩu",
  "Dâu tây nhập khẩu",
  "Lựu nhập khẩu",
];
