export const urls = [
  "https://shopeefood.vn/da-nang/kho-ga-la-chanh-shop-online",
  "https://shopeefood.vn/da-nang/tiem-an-vat-nha-dau-do-an-vat-nhap-khau-nguyen-huu-tien.cta8nn",
  "https://shopeefood.vn/da-nang/quay-cu-qua-gia-vi-duong-nguyen-nhan.flojhd",
  "https://shopeefood.vn/da-nang/thuc-pham-sach-hoang-linh-food-ga-u-muoi-me-thu",
  "https://shopeefood.vn/da-nang/bach-hoa-lam-banh-anton-bau-tram-3",
  "https://shopeefood.vn/da-nang/chinn-s-food-nguyen-lieu-tokkbokki",
  "https://shopeefood.vn/da-nang/shop-rau-qua-yen-tieu-la",
  "https://shopeefood.vn/da-nang/dac-san-3-mien-hoang-dieu",
  "https://shopeefood.vn/da-nang/tiem-an-ah-ca-set-tra-sua-do-an-vat-dang-tat",
  "https://shopeefood.vn/da-nang/meo-kho-ga-la-chanh-shop-online",
  "https://shopeefood.vn/da-nang/laban-mart-chau-thi-vinh-te",
  "https://shopeefood.vn/da-nang/kim-lien-minimart",
  "https://shopeefood.vn/da-nang/a-nam-chuyen-ga-tuoi-song",
  "https://shopeefood.vn/da-nang/kim-chi-han-quoc-nha-rot",
  "https://shopeefood.vn/da-nang/andros-trai-cay-tuoi-dong-lanh-ly-nhat-quang",
  "https://shopeefood.vn/da-nang/van-mart-thuc-pham-dong-lanh-57-dong-giang",
  "https://shopeefood.vn/da-nang/danh-tap-hoa-tieu-dung",
  "https://shopeefood.vn/da-nang/sieu-thi-co-op-mart-da-nang",
  "https://shopeefood.vn/da-nang/shop-me-soc-thuc-pham-sua",
  "https://shopeefood.vn/da-nang/co-tam-cha-bo-cha-heo-nguyen-kha-trac",
  "https://shopeefood.vn/da-nang/pate-loan-nguyen-pate-ca-phe-pha-san-shop-online",
];

export const foodKeyWords = [
  "Khô gà lá chanh",
  "Set rìa chấm sốt",
  "Phơi sương bột gạo",
  "Bánh rìa",
  "Bánh tráng tắc Bon",
  "Bánh tráng phơi sương",
  "Bánh tráng bơ",
  "Phơi sương dẻo chấm",
  "Set rìa chấm chanh",
  "Bơ",
  "Sốt me nhà nấu",
  "Bánh tráng bơ khô",
  "Bánh tráng phô mai",
  "Đậu lộn xộn",
  "Rôm chay",
  "Nước mắm chay Cholimex",
  "Chao môn",
  "Bột ngột nomoto",
  "Hạt nêm ngon",
  "Nước tương Hương Việt",
  "Giá vị bún bò",
  "Nước tương đậu nành",
  "Nước mắn Nam Ngư",
  "Gia vị thịt kho",
  "Bột năng",
  "Xốt bò kho Cholimex",
  "Xốt rang me Cholimex",
  "Tương cà chinsu",
  "Tương ớt chinsu",
  "Sứa",
  "Chả nấm",
  "Xúc xích chay",
  "Phù chúc lá",
  "Ống mì căn",
  "Chả phù chúc nhỏ",
  "Bột canh Ajnomoto",
  "Dầu ",
  "Bột chiên giòn Aji",
  "Tương ớt ngọt",
  "Bột ngột a-one",
  "Nước tương Tam Thái",
  "Gà ta xông khói",
  "Gà ta ủ muối",
  "Chân gà rút xương",
  "Bột ca cao nguyên",
  "Bột quế nguyên chất",
  "Hỗn hợp Hương Màu",
  "Hương Caramel / Tinh",
  "Hương Chuối / Tinh",
  "Baking Soda đa công",
  "Bột Nổi / Bột",
  "Bột nổi / Bột",
  "Men khô Ngọt đầu",
  "Men khô ngọt Mauripan",
  "Men khô Lạt đầu",
  "Bột Mì Bakers' Choice",
  "Giá ưu đãi -",
  "Bột Gạo Tài Ký",
  "Bột cốt dừa nguyên",
  "Kem Phô mai/ Cream",
  "Hạnh nhân Lát Olam",
  "Bơ lạt Anchor chia",
  "Hương Vanilla Rayner’s",
  "Bột Trà Xanh Matcha",
  "Hương Dừacoconut) /",
  "Tinh Bột Bắp/ Bột",
  "Giá ưu đãi Bột",
  "Bột Năng Tài Ký",
  "Bột trộn sẵn Bánh",
  "Bột mì đen Cao",
  "Socola chip Đen chia",
  "Bột Phô mai/ Fomai",
  "Phô mai bào Zelachi",
  "Bột Whipping Cream Snow",
  "Hồ lô",
  "Mực viên Hàn Quốc",
  "Khoai tây chiên gói",
  "Ốc nhồi",
  "Hoành thánh",
  "Tàu hủ cá nhân",
  "Sò điệp Lichuan gói",
  "Cá viên Singapore gói",
  "Pho mai bào sợi",
  "Set bánh gạo thường",
  "Pizza bò",
  "Nem chua rán hộp",
  "Xúc xích LC",
  "Tôm con surimi",
  "Viên thả lẩu trứng",
  "Set nhúng lẩu/chiên mắm",
  "Tàu hủ cá LC",
  "Sốt nấu kèm TOKBOKKI",
  "Pizza xúc xích",
  "Bánh tráng ruốc Đà",
  "Bánh gà nhân pho",
  "Đùi gà",
  "Cánh gà",
  "Gà cuộn rong biển",
  "Trứng Vịt 5 Cái",
  "Mì Quảng",
  "Trứng gà ác- 1",
  "Đậu Phụng Rang Sẵn",
  "Bún Khô",
  "Nghệ Tươi",
  "Bánh Tráng Đại Lộc",
  "Bột Chiên Giòn",
  "Bánh Bía",
  "Nước Tương magi chai",
  "Xốt Ướp Thịt nướng",
  "Mì Omachi Bò Hầm",
  "Mè Rang Sẵn 1",
  "Mắm Chin Su Thủy",
  "Nếp Cái Hoa Vàng",
  "Bột Rau Cau Dẻo",
  "Nui Cọng Dài",
  "Đường Cát Trắng 1/2",
  "Gia Vị Bò Kho",
  "Mì Trứng Safoco",
  "Phở Khô",
  "Nước Tương Đậm Đặc",
  "Bột trà xanhgói",
  "Set rìa chấm ớt",
  "Sốt chanh dây mật",
  "Bánh tráng xì ke",
  "Cơm cháy + khô",
  "Xâu vò Gia Lai",
  "Set phơi sương thập",
  "Bánh tráng ớt tắc",
  "Xì ke tỏi bò",
  "Dầu hào chay Maggie",
  "Chả chén",
  "Rôm vừa",
  "Rôm lớn",
  "Dầu ăn Neptune",
  "Bột cà ri",
  "Nước mắm Hương Việt",
  "Muối ông già",
  "Hạt nêm Maggi",
  "Giá vị cá kho",
  "Dầu cái lân",
  "Giá vị kho thịt",
  "Xốt ướp xá xíu",
  "Giá vị kho cá",
  "Rong biển",
  "Trứng gà",
  "Chả phù chúc lớn",
  "Chả viên",
  "Muối ngọc yến",
  "Đường phèn",
  "Đường",
  "Giá vị lẩu thái",
  "Ma - dô -",
  "Xôi chim",
  "Chân gà ủ muối",
  "Búp bò xông khói",
  "Giò heo rút xương",
  "Kularome sữa, hương sữa",
  "Bột Nếp Tài Ký",
  "Bột Kem Béo Hà",
  "Kem Rich Lùn /",
  "Bột sư tử, Bột",
  "Chất Ổn Định Bánh",
  "Đường Xay/ Đường bột",
  "Men Nở, Men Khô",
  "Bột Baking Soda Đa",
  "Men khô lạt Mauripan",
  "Bơ thơm cái lân",
  "Hạnh Nhân Bột Olam",
  "Bột cơm dừa sấy",
  "Thìa Muỗng Lọc Trứng",
  "Dồi sụn Hà Thành",
  "Chả mực xoắn ống",
  "Bánh sữa tươi chiên",
  "Pho mai viên",
  "Chạo sả",
  "Ba chỉ bò Mỹ",
  "Thanh cua",
  "Bột pho mai Osajang",
  "Cá viên rau củ",
  "Há cảo",
  "Viên thả lẩu mix",
  "Bánh gạo không nhân",
  "Chả cá Hàn Quốc",
  "Bánh gạo nhân pho",
  "Set bánh gạo pho",
  "Tôm Bạc Size Vừa",
  "Muối 2 Gói",
  "Mắm Nêm Dì Cẩn",
  "Rong Biển",
  "Bột Ngũ Vị Hương",
  "BánhTráng Nướng Mè Đen",
  "Tương Ớt hội an",
  "Gạo Cỏ Mây 10",
  "Mì Hảo Hảo Ly",
  "Bột Ngọt A-one",
  "Gạo Thơm Lài Sữa",
  "Bột Cà Ry",
  "Đường Phèn 1/2 Kg",
  "Nước Cốt Dừa Lon",
  "Bột Bắp",
  "Đậu Đen Xanh Lòng",
  "Mayonaise",
  "Tương Ớt Cholimex",
  "Tinh bột nghệgói",
  "Ủ Trắng Cà Phê",
  "SET Rìa Muối nhuyễn",
  "Bơ gói 100g",
  "TÓP MỠ HŨ",
  "Ớt rim mật ong",
  "Sốt me cay",
  "Bánh tráng dẻo tôm",
  "Sốt tắc",
  "Bánh tráng vò sợi",
  "Chả rong biển",
  "Bột canh nấm bào",
  "Nước mắm Đệ nhị",
  "Mắm nêm dì cẩn",
  "Tương ớt chinsu",
  "Xì dầu Maggie",
  "Dầu giấm Cholimex",
  "Khoai lang vàng",
  "Trứng vịt",
  "Sườn dừa",
  "Nước mắm Nam ngư",
  "Giấm",
  "Giò heo xông khói",
  "Gà ủ muối khay",
  "KULAROME HƯƠNG MÀU LÁ",
  "Bột nổi /Bột nở",
  "Bột năng cao cấp",
  "Set 6 Khuôn Cupcake",
  "Khuôn Làm Bánh Oval",
  "Phụ gia bánh mì",
  "Hương Bạc Hà/ Tinh",
  "Bột bánh mì số",
  "Tôm viên chiên",
  "Pho maii que",
  "Khoai lang kén",
  "Viên thả lẩu nhân",
  "Bánh gà truyền thống",
  "Viên tôm hùm EB",
  "Ớt Bột Hột",
  "Đậu Phộng Sống 1",
  "Bánh Tráng Mềm",
  "Bột Bánh Canh Khô",
  "Dầu Simply",
  "Mắm Nam Ngư",
  "Dầu Neptune",
  "Bánh tráng mè Đen",
  "Hạt Nêm Xương Know",
  "Mắm Ruốc Ngon",
  "Bột Bánh Xèo",
  "Gói Nấu Lẫu Thái",
  "Nước Mắm Đệ Nhị",
  "Nui Safoco",
  "Bánh Tráng Lề",
  "Bột Chiên Xù",
  "Ớt Bột Mịn",
  "Nước Tương Maggi ",
  "Muối Hạt Sống 1",
  "Đậu Xanh Cà Vỏ",
  "Miến Dong Phương Thùy",
  "Đậu Xanh 1 Lon",
  "Dầu Hào ",
  "Bánh Tráng Gói Ram",
  "Đường Tinh Luyện Biên",
  "Xốt Me Cholimex",
  "Gạo St 25",
  "Set dẻo tôm thập",
  "Bánh tráng sấy tép",
  "Cơm cháy mắm ớt",
  "Măng khô",
  "Chao Bông Mai",
  "Ngũ vị hương",
  "Xốt ướp thịt nướng",
  "Bột mì số 8",
  "Sales Bột trộn sẵn",
  "Cá viên chiên",
  "Chả cốm Hà Nội",
  "Bắp Mỹ tách hạt",
  "Xúc xích Đức cao",
  "Hải sản cốm xanh",
  "Thanh cua",
  "Set mix cá, bò,",
  "Viên mặt cười",
  "Đậu khuôn - 1",
  "Trứng cút - 1",
  "Sữa đặc lon ngôi",
  "Mì Hảo Hảo Chua",
  "Tiêu Xay",
  "Đường Cát Trắng 1",
  "Tương Ớt Chin Su",
  "Nấm Mèo",
  "Hành Phi 1 Lạng",
  "Sa Tế tôm Xo",
  "Dầu Hào ",
  "Bột Mì ",
  "Dấm Gạo",
  "Mì Omachi Sườn Hầm",
  "Ớt Bột Điều",
  "Cá Hộp",
  "Bột Năng",
  "Tương Cà Cholimex",
  "Muối Tây Ninh 1",
  "Bánh Tráng Nướng Gạo",
  "Chao Nhà Làm",
  "Giấm Gạo",
  "Bơ Tường An",
  "Muối Xí Muội",
  "Heo Hầm 1 Hộp",
  "Xốt Ướp Thịt Nướng",
  "Muối Sấy Chấm Trái",
  "Sốt Ướp Thịt Xá",
  "Mì ký Milyket",
  "Thịt Heo Xay 1",
  "Thịt Heo Ba Chỉ",
  "Thịt Sườn Heo 1/2",
  "Thịt Heo Nạt 1",
  "Gà Tam Hoàng 1",
  "Thịt Xương Cổ Heo",
  "Vịt làm sạch",
  "Bánh tai heo Chiên",
  "Bánh tai heo ngọt",
  "Hạt Bí Rang Muối",
  "Nước Ép Ổi Chai",
  "Mắm Dưa Chay",
  "Cá cơm khô 1",
  "Xốt Lẩu Chua Hải",
  "Dầu tường ăn 400ml",
  "Mì Ý Pasta Zara",
  "Xốt Mè Rang 1",
  "Bột canh hương gà",
  "Thịt Heo Vai 1/2",
  "Bánh Gạo Nhật Gói",
  "Bánh Quẩy Đường 1",
  "Hạt Dưa Trường Đạt",
  "Bánh dẻo gừng 1",
  "Hạt Dẻ Cười 1/2",
  "Nước Mía Ly To",
  "Nước Mía Sạch 1",
  "Chả Lụa Chay 1",
  "Chả Nấm Chay",
  "Phù chúc khô 1",
  "Kẹo đậu - 5cái",
  "Bánh tráng sữa",
  "Mè xửng giòn",
  "Bánh Tráng Bò Khô",
  "Bánh tráng chuối",
  "Bánh đậu xanh lạc",
  "Bánh đậu xanh ngọt",
  "Xoài Sấy Dẻo",
  "Cơm cháy siêu chà",
  "Banh tráng dừa nướng",
  "Bánh tráng mè đen",
  "Bánh Dẻo Củ Sen",
  "Mực 1 nắng túi",
  "Ghẹ sữa - 1",
  "Cá bò rim",
  "Mực Rim Đặc Biệt",
  "Gà xé sợi -",
  "Muối ớt xanh -",
  "Cá thu que -",
  "Cá cơm -r",
  "Bò viên rim Ước",
  "Tôm sú đặc biệt",
  "Tinh dầu sả1",
  "Dừa nướng",
  "Kẹo dừa",
  "Mứt me mãng cầu",
  "Mứt me sấy -",
  "Xoài sấy dẻo hộp",
  "Dừa sợi non vị",
  "Cá mú tẩm",
  "Bò khô phi lê",
  "Bánh quế",
  "Mực xé sợi -",
  "Cá chỉ vàng tẩm",
  "Mực Hấp Xé Sợi",
  "Set nguyên liệu pha",
  "Xúc xích ngon -",
  "Nem chua rán -",
  "GÀ Ủ MUỐI HOA",
  "Bánh gấu ruốc -",
  "Mandu thịt ngon hàn",
  "Set thả lẩu- 30viên",
  "Bánh gạo cay truyền",
  "Khoai tây chiên 1kg",
  "Bánh mix vị lộn",
  "Cá viênr",
  "Bánh Liu Xin Su",
  "Tôm viênram",
  "Khô gà - 1",
  "Táo xanh Hộp",
  "Sữa chua uống có",
  "Thanh gạo lứt hạt",
  "Thịt heo xay Vietgap",
  "Sườn Non Heo VietGap",
  "Xương ống heo Vietgap",
  "Bột Gạo",
  "Đường Mía Biên Hoà",
  "Tương ớt tươi nhà",
  "Nước tương tam thái",
  "Muối ớt chanh",
  "Phở Khô Miliket",
  "Xốt Cary Dầu",
  "Bánh phồng tôm 10%",
  "Thịt Bò Mềm 1",
  "Thịt Bò Gân 1",
  "Ram Tôm Đất size",
  "Thịt Xương Đuôi Heo",
  "Thịt Xương Ống Heo",
  "Thịt Sườn Heo 1",
  "Xúc Xích heo Bonie",
  "Bánh Thèo Lèo",
  "Khô Gà Xé",
  "Bò Khô Lát",
  "Đậu hủ non -",
  "Chả Chén Chay 1",
  "Chả Phù Chúc Chay",
  "Mayonnaise Chai Nhỏ",
  "Dầu Dấm",
  "Đậu Đỏ Hạt Nhỏ",
  "Xốt Bò Kho Hủ",
  "Mì trộn cung đình kool",
  "Gạo Lức Tím Than",
  "Ram Tôm Loại Nhỏ",
  "Gà ta thả vườn",
  "Bánh Cua Chiên Mắm",
  "Hạt dưa Thái Sơn",
  "Nem Chay 1 Lát",
  "Hạt Nêm Nấm Chay",
  "Ram Chay Bánh Rế",
  "Bánh xoài",
  "Bánh Bía Chay",
  "Kẹo dừa bến tre",
  "Bánh Dẻo Sữa Dừa",
  "Dừa non vị dứa",
  "Keo cu Đơ",
  "Bánh ép huế",
  "Mực xé sợi hộp",
  "Bánh đậu xanh hải",
  "Mực rim me -",
  "Mực cán Ăn Liền",
  "Cá bò tẩm ăn",
  "Cá Bống Rim 300g",
  "Muối Tôm Ăn Trái",
  "Tép Khô",
  "Cá cơm rút xương",
  "Bánh tráng cuốn",
  "Mực Cán Rim 300g",
  "Tinh dầu tràm1",
  "Tinh dầu quế1",
  "Bánh đậu xanh mặn",
  "Xoài sấy",
  "Bánh hạt điều",
  "Kẹo đậu phộng tròn",
  "Cá bò que",
  "Mực 1 nắng",
  "Mực xé sợi ăn",
  "Bò khô lát phi",
  "Cá thiều que -",
  "Cá thu tẩm",
  "Mắn ruốc",
  "Pudding 3vị socola/môn/trứng",
  "Phomai que - 10/que",
  "Bánh gấu ruốc đài",
  "BÁNH MÌ HOA CÚC",
  "Trân châu đen gói",
  "Trân châu trắng gói",
  "Dẻ sườn bò cắt",
  "Hành Phi Thanh Sang",
  "Canh Bí Đỏ Thịt",
  "Canh Bí Đao Sườn",
  "Canh Bí Đao Thịt",
  "Canh Bầu Ta Tôm",
  "Canh Bí Đỏ Sườn",
  "Đậu Khuôn miếng lớn",
  "Sữa Chua Ăn Ít",
  "Sữa Tươi tiệt trùng",
  "Sữa đặc nhập khẩu",
  "Thịt Ba Rọi Heo",
  "Thịt đùi heo Vietgap",
  "Chân Giò Heo Vietgap",
  "Đường Phèn 1 Kg",
  "Bột Đông Sương",
  "Bánh tráng safoco",
  "Nuôi ",
  "Xúc xích bò visan",
  "Mắm Nêm Cá Thu",
  "Cốt Me gói",
  "Sa Tế Chay",
  "Bún gạo lức 1",
  "Tương ớt xí muội",
  "Thịt Heo Mông 1/2",
  "Chả Quết Bò 1",
  "Thịt Cốt Lết 1/2",
  "Chả Cá Thu Chiên",
  "Chả Bò 1/2 Kg",
  "Thịt Giò Heo 1",
  "Bánh Thèo Lèo 1",
  "Bánh Tai Heo Chiên",
  "Hạt Dẻ Cười 1",
  "Nước Suối Aquafina 500ml",
  "Chả cá viên chạy",
  "Tương ớt chinsu chai",
  "Bò Hầm 1 Hộp",
  "Bánh Tráng Mè Đen",
  "Sữa đặc ông thọ",
  "Bánh Dẻo Sữa 1",
  "Cá Thu Chay 1",
  "Bánh đậu xanh Thanh",
  "Kẹo chuối",
  "Bánh Tráng Tôm Dẻo",
  "Bánh đậu phộng loại",
  "Cơm cháy chiên",
  "Kẹo xoài",
  "Bánh hạt sen",
  "Tương ớt rim -",
  "Bánh tráng đại lộc",
  "Cá bò -r",
  "Bò Thu Ba",
  "Cá mai - 1",
  "Bánh dừa nướng Xuất",
  "Bánh Dẻo Khoai Môn",
  "Bánh dừa sợi non",
  "Bánh tráng tôm",
  "Trà sâm dứa -",
  "Bánh gạo cay pho",
  "Viên chiên mix tổng",
  "Khô gà - 3",
  "Khô gà - 5",
  "Sườn non bò cắt",
  "Wasabi Nhật S&b 43g",
  "Đu đủ nấu canh",
  "Canh Củ Quả Sườn",
  "Canh Khổ Qua Thịt",
  "Canh Củ Quả Xương",
  "Canh Bí Đao Xương",
  "Canh Bí Đỏ Xương",
  "Xương Heo Nhiều Thịt",
  "Thịt Heo Xay Vietgap",
  "Thịt thăn heo Vietgap",
  "Cốt Lết Heo Có",
  "Gia vị bún bò",
  "Thịt Heo Mông 3",
  "Gà Cánh Nhỏ 1",
  "Gà Trống Thường Cún",
  "Mè xửng Huế",
  "Bánh Bía Trứng Muối",
  "Mực 1 nắng hộp",
  "Mắm tôm chua -",
  "Bò Phi Lê",
  "Bò Viên Khô",
  "Trà sâm túi lọc",
  "Nước chấm đậu nành",
  "Tàu Hũ Non Ichiban",
  "Chanh Dây -1kg",
  "Táo Gala New- ",
  "Khổ Qua Bào Lát",
  "Mướp hương cắt sẵn",
  "Set rau ăn lẩu",
  "Canh Củ Quả Thịt",
  "Canh Bí Đỏ Tôm",
  "Thịt Đùi Heo Vietgap",
  "Thịt Vai Heo Vietgap",
  "Xương Ống Heo Vietgap",
  "Thịt Thăn Heo Vietgap",
  "Tim Heo Nhập Khẩu",
  "Ba Chỉ Bò Mỹ",
  "Thịt bò nhập khẩu",
  "Đùi gà mềm nhập",
  "Gà Đèo Le làm",
  "Chân Gà Rút Xương",
  "Gà Ta Thả Vườn",
  "Chả Cua Huế",
  "Cá Nục Nhật Bản",
  "Xúc Xích Chiên Zing",
  "Cá Viên CP gói",
  "Bò viên LC Food",
  "Khoai lang kén Thiên",
  "Trứng Gà Ta 4",
  "Cá chỉ vàng rim",
  "Mực Xé Tẩm Nước",
  "Bột Bánh Xèo Gói",
  "Mì Trứng thượng hạng",
  "Bột năng Tài Ký",
  "Bột gạo - Gói",
  "Mì dinh dưỡng khoai",
  "Gạo ST ogarnictúi",
  "Mì Omachi xốt Spaghetti",
  "Gia Vị Hoàn Chỉnh",
  "Dầu Hào Cholimex -",
  "Muối Tinh i ốt",
  "Màu dầu điều -",
  "Bột Canh Nấm Bào",
  "Dầu Tường An Cooking",
  "Nước Chấm Kewpie Mè",
  "Bột Ngọt Vedan Gói",
  "Nước Mắm Nam Ngư",
  "Tương chấm ăn liền",
  "Xốt Mayonaise Kewpie 130g",
  "Nước Tương Đạm Đặc",
  "Dầu ăn Neptune Light",
  "Mỡ Heo Vietgap -",
  "Thịt Heo Xay Nhập",
  "Ba chỉ heo Rút",
  "Bắp Giò Heo Nhập",
  "Thịt heo nhập khẩu",
  "Lõi Vai Bò Mỹ",
  "Đùi tỏi gà Mỹ",
  "Gà Ta Lai Nguyên",
  "Chân Gà Nhập Khẩu",
  "Bồ Câu Nguyên Con",
  "Cá Ngừ Thu Cắt",
  "Set lẩu hải sản",
  "Xúc Xích CP RED",
  "Tôm viên LC food",
  "Mì Trứng  ~",
  "Mì tôm Kokomi chua",
  "Gạo Cỏ May Bao",
  "Bánh Tráng Gỏi Cuốn",
  "Nui Ống Dài ",
  "Móng Heo Nhập Khẩu",
  "Ba Chỉ Heo Nhập",
  "Sườn Non Heo Nhập",
  "Bắp Bò Úc Bào",
  "Bắp Bò Úc Cắt",
  "Bò Xay Nhập Khẩu",
  "Ức Gà 300g",
  "Gà Ác Nguyên Con",
  "Cá Basa Cắt Lát",
  "Mực Vòng Nhập Khẩu",
  "Diêu Hồng Con To",
  "Cá Nục Hoa Nhật",
  "Lườn Cá Hồi Nhập",
  "cá viên rau củ",
  "Cá viên LC Food",
  "Trứng Gà Ta -",
  "Mực rim me Đà",
  "Cá Bò Rim",
  "Bún Tươi Safoco Gói",
  "Gạo ST25 Tân Long",
  "Bột Bắp Tài Ký",
  "Gạo Nếp Cái Hoa",
  "Bột nếp - Gói",
  "Bún Khô Gạo Lứt",
  "Bánh tráng không nhúng",
  "Bột Chiên Giòn ",
  "Mỳ Spaghetti Ankara)",
  "Nui Safaco",
  "Gạo Tài Nguyên thơm",
  "Gia Vị Kho Thịt",
  "Tương Ớt Cholimex Chai",
  "Xốt Uớp Thịt Nướng",
  "Tương Cà Cholimex 270g",
  "Xì dầu tam thái",
  "Ớt Sate Cholimex ",
  "Xì Dầu Tam Thái",
  "Xốt Rang Me Cholimex",
  "Tương Ớt Chinsu",
  "Bơ Thực Vật ",
  "Nước Dùng Hoàn Chỉnh",
  "Dầu Đậu Nành Tường",
  "Sốt ướp sườn heo",
  "Mắm Ruốc Duy Trịnh",
  "Dầu Gạo Lứt Nguyên",
  "Nước Cốt Dừa VIETCOCO",
  "Tương Ớt Rim Nhật",
  "Tương Ớt Rim Hội",
  "Đường Vàng Tinh Khiết",
  "Set nướng ba chỉ",
  "Sườn Non heo Nhập",
  "Cốt Lết Heo Nhập",
  "Heo Xay Nhập Khẩu",
  "Thăn Ngoại Bò Úc",
  "Cánh Gà Nhập Khẩu",
  "Chả Cá Lý Sơn",
  "Cá Chim Cắt Lát",
  "Cá Lóc Làm Sạch",
  "Da Lưng Heo Vietgap",
  "Bắp bò Úc Cắt",
  "Cánh Gà Giữa Nhập",
  "Vịt cỏ thả đồng",
  "Tôm Bạc Hút Chân",
  "Trứng Gà Sạch An",
  "Cá Bò Xé",
  "Mực Cán Xé",
  "Nếp Thái Loại Ngon",
  "Gạo Thơm Mai Xanh",
  "Gạo St25 Sumi &",
  "Bột mì  _gói",
  "Bơ thực vật Margarine",
  "Hạt Nêm Từ Thịt",
  "Nước Dùng Cô Đặc",
  "Gia Vị Kho Cá",
  "Hạt nêm từ thịt",
  "Dầu đậu nành Simply",
  "Xốt Bò Kho Cholimex",
  "Gia vị hoàn chỉnh",
  "Đường Mía Vàng Cô",
  "Dầu Thực Vật Tường",
  "Đường Trắng Thượng Hạng",
  "Nước Xốt Kewpie 210ml",
  "Tương ớt tươi Hot",
  "Xà Lách Xoăn -",
  "Thịt heo Vietgap thái",
  "Thịt nạc vai heo",
  "Khoai Tây Nhập Khẩu",
  "Chả Ram Tôm Đất",
  "Vịt Quê Nguyên Con",
  "Dồi Sụn Hà Thành",
  "Trứng Cút 20 quả",
  "Cơm Cháy Chà Bông",
  "Kimpap cuộn Kfood",
  "Tiêu Đen Xay Gói",
  "Muối Tôm Tây Ninh",
  "Dầu ăn cao cấp",
  "Đường Mía Trắng Cô",
  "Dầu Dấm Trộn Salad",
  "Tương chấm thịt nướng",
  "Nước Tương Đậu Nành",
  "Sốt ướp sườn bò",
  "Xốt Ướp Xá Xíu",
  "Lá Hương Thảo Khô",
  "Ớt Bột Hàn Quốc",
  "Đường Phèn Tinh Khiết",
  "Tỏi Bột Nature DH",
  "Bột Điều Đỏ Nature",
  "Dầu Ăn Dinh Dưỡng",
  "Gia Vị Nấu Bún",
  "Gia Vị Nấu Phở",
  "Mắm Cá Cơm Duy",
  "Gà ta lai con",
  "OR Bánh Gạo Nướng",
  "Richy Karo 21% Sợi",
  "Or choco-pie vị Cacao",
  "Or MIZ Bánh Quy",
  "Bánh quy sữa cosy",
  "KD Cosy Marie 288g",
  "AFC vị bò bít",
  "Snickers 35g",
  "Hall XS Kẹo Ngậm",
  "Xyliton Cool 11.6g",
  "Coolair Hương Bạc Hà",
  "DoubleMint Gum Bạc Hà",
  "Tân Tân Đậu Phộng",
  "Or Marine Boy Tôm",
  "Bento Spicy Larb",
  "Bento Hot&spicy 24g",
  "Mix Nori Seaweed Biscuit",
  "Bento Sợi Mực Tẩm",
  "Calbee Ngũ Cốc Hàn",
  "Lay's Vị Gà Cay",
  "Lay's Vị Thăn Bò",
  "Bỏng Ngô Mỹ Vị",
  "Or bánh gạo nướng",
  "Bánh gạo one one",
  "C'est bon bánh ăn",
  "Or goute 288g",
  "Or goute 144g",
  "Cosy bánh quế vị",
  "Oreo original 133g",
  "AFC vị lúa mì",
  "Oreo ice cream việt",
  "Lotte toppo cocoa chocolate",
  "Lotte Koala's March White",
  "Striking Cola",
  "Striking Blueberry",
  "Kopiko Cappucino Candy 135g",
  "Dairy Milk Black Forest",
  "Kopiko Caffee Candy 135g",
  "Cool Air Hương Bạc",
  "Extra Bạc Hà 11.8g",
  "Bento Super Spicy Seafood",
  "Bento Sweet&spicy",
  "Mực Hấp Dừa",
  "Swing Vị Gà Teyariky",
  "Lay's Vị Tảo Biển",
  "Mì Modem Lẩu Thái",
  "Mì Cung Đình Lẩu",
  "Mì Lẩu Thái Hương",
  "Miến Phú Hương Sườn",
  "Mì Lẩu Reeva Nấm",
  "VF Cháo Sườn 70g",
  "Nissin Mì Cay Xào",
  "Vissan Xúc Xích Bò",
  "Cá Hộp 3 Cô",
  "Visan Heo 2 Lát",
  "Visan Thịt Heo Hầm",
  "Maggi Nước Tương Đậu",
  "Tường An Gold 1l",
  "Dầu Đậu Nành Simply",
  "Maggi Hạt Nêm Nấm",
  "Bột Gia Vị Ngũ",
  "Mayonnaise 130g",
  "Ajinomoto 400g",
  "Bột Ngọt Ajinomoto 100g",
  "Tiêu Đen Xay",
  "Tiêu Trắng Xay",
  "Nước Mắm Truyền Thống",
  "Muối Ớt Chanh Nha",
  "Chillica Ớt Bằm Tự",
  "Hảo Hảo Tôm Chua",
  "Mì Cung Đình Vị",
  "Omachi Bò Hầm 80g",
  "Vf Phở Bò 65g",
  "Visan Bò 2 Lát",
  "Dầu Ăn Neptune Light",
  "Chinsu Nam Ngư 500ml",
  "Chinsu Nam Ngư 750ml",
  "Kewpie Nước Chấm Mè",
  "Tường An Bơ Thực",
  "Chinsu Nam Ngư Phú",
  "Xốt Ướp Sườn",
  "Sa Tế Tôm",
  "Muối Chấm Hoa Quả",
  "Ớt Chỉ Thiên Xay",
  "Tường An Cooking Oil",
  "Kewpie Xốt Mè Rang",
  "Cà Ri Xanh",
  "Bánh gạo Nhật Ichi",
  "Richy Freshta Potato Sandwich",
  "Or choco-pie 396g",
  "Or choco-pie 198g",
  "Oreo chocolate 137g",
  "Oreo Original 199,5g",
  "Doublemint Viên Ngậm Hương",
  "M&M Milk Chocolate 14,5g",
  "M&M Peanut Đậu Phộng",
  "Striking Lychee",
  "Kẹo Thạch Zaizai ",
  "Xylitol Hương Blueberry Mint",
  "Xyliton H.blueberry Mint 11.6g",
  "Xyliton H.lime Mint 11.6g",
  "Bento Namprik Thai Original",
  "Me Muối Ớt Cay",
  "Lay's Sườn Nướng Bbq",
  "M&M milk Chocolate 37g",
  "Dairy Milk Roast Almond",
  "Skittles 100g",
  "Skittles 15g",
  "Striking Lemon",
  "Xylitol Hương Lime Mint",
  "Xylitol Hương Strawberry Mint",
  "Xylitol Cool 58g",
  "Lương khô 5+",
  "Or Marine Boy Vị",
  "Bento Angry Spicy",
  "Mực Rim Sa Tế",
  "Mix Smoked Bacon Biscuit",
  "Mix Limited Edition",
  "Omachi Speacial Bò Hầm",
  "Omachi Sườn Hầm Ngũ",
  "Omachi Xốt Tôm Chua",
  "HF Bún Gạo Lứt",
  "Nissin Mì Xào Hương",
  "Dầu Ăn Tường An",
  "Vf Muối Iot Cao",
  "Hạt Nêm Knorr 170g",
  "VF Bột Canh",
  "Phở Bò",
  "Bột Tẩm Chiên",
  "Vietcoco Nước Cốt Dừa",
  "Maggi Dầu Hào",
  "Bột Ngọt",
  "Giấm Táo",
  "Xốt Ướp Thịt",
  "VF Bột Canh Iot",
  "Sa Tế Cay",
  "Dầu Mè Thơm ",
  "Tường An Dầu Đậu",
  "Phở Bò Đệ Nhất",
  "Vf Cháo Thịt Bằm",
  "Miến Phú Hương Yến",
  "VF Cháo Thịt Gà",
  "Visan Bò Hầm",
  "EF mật Ong Tam",
  "Tương Ớt Chinsu",
  "Chinsu Đệ Nhị",
  "Dầu Ăn",
  "Lẩu Thái",
  "Biên Hòa Đường Mía",
  "Hạt Nêm Knorr 900g",
  "Tiêu Đen Xay Loại",
  "Aji Ngon Hạt Nêm",
  "Muối Ớt Tây Ninh",
  "Ớt Bột",
  "Muối Tiêu Chanh Ớt",
  "Muối Tiêu Tây Ninh",
  "Chân gà",
  "Nước Ép Thạch Đào",
  "Chunky Nho chuỗi ngọc",
  "Trái mọng tổng hợp",
  "Pho Mai Que Cốm",
  "BÁNH BAO NHÍM",
  "SÒ ĐIỆP 1kg",
  "Trà Sữa Trân Châu",
  "Nem Chua Rán Phần",
  "Chả Cá Bọc Cốm/",
  "ỐC NHỒI",
  "Bánh Gạo Hàn Quốc",
  "TÔM VIÊN/ 4 Viên",
  "Bánh Bao Trứng Muối",
  "TÔM VIÊN nữa Ký",
  "Bánh Bao Kim Sa",
  "Kimbap/ 5 Miếng",
  "HỒ LÔ / 3",
  "Mực Viên",
  "PHO MAI QUE",
  "PHO MAI QUE CỐM",
  "Sủi Cảo Chiên /12",
  "Gạo A An -",
  "Đậu phụng da cá",
  "Bánh Quy Phô Mai",
  "kẹo nổ StriKing vị",
  "Gà nguyên con",
  "Lay's Stax Lon Đủ",
  "Nửa con gà",
  "Bánh Tráng Tôm Hành",
  "Kim chi cải thảo",
  "Kẹo Gum DoubleMint Bạc",
  "Mâm xôi đen đông",
  "Nước tăng lực Number",
  "Sting dâu",
  "Việt quất trái lớn",
  "Việt quất thiên nhiên",
  "Revive Chanh Muối",
  "Sữa yomost hương cam",
  "Dâu tây đông lạnh",
  "Xúc Xích O.5kg",
  "CÁ VIÊN O,5KG",
  "Sữa trái cây Nutri",
  "Mirinda hương cam 1.5",
  "Hồ Lô Loại 2",
  "Mì tôm đặc biệt",
  "Phở bò VIFON gói",
  "Khoai Lang Kén",
  "Phở bò hà nội",
  "Mì trộn khô hộp",
  "Pho Mai Que 20",
  "Sò Điệp /3 Viên",
  "Cháo tổ Yến Vietnest",
  "Xx lắc heo cao",
  "Sữa Tươi Chiên",
  "Trà Bí Đao Hạt",
  "BÒ VIÊN / 4",
  "THANH CUA Nữa",
  "TÔM VIÊN",
  "Bánh Bao Chiên Nhân",
  "Bò Viên Nữa",
  "Xúc Xích / 1",
  "Khoai Môn Lệ Phố",
  "CÁ VIÊN /4 VIÊN",
  "Gạo thơm quê 10kg",
  "Nếp thơm hạt to",
  "Bánh lays đủ vị",
  "Hạt xí mụi mặn",
  "Bánh gạo nướng An",
  "Bánh nabati )",
  "Bánh trứng Custas kem",
  "Bánh gạo rong biển",
  "Dầu Neptune Gold",
  "Dầu cái lân 1L",
  "Dầu phụng quê nguyên",
  "Dầu CookingOil Trường An",
  "Muối Tinh I ỐT",
  "Bột tiêu",
  "Đường cát trắng 1kg",
  "Tương ớt Chin-Su",
  "Nước mắm nam ngư",
  "Bột ngọ mì chính",
  "Gia vị nêm sẵn",
  "Bột rau cau dẻo",
  "Hạt nêm Knorr thịt",
  "Chao đậu 170g",
  "Bột cốt dừa",
  "Nấm Mèo 1",
  "Tiêu Đen Xayklt",
  "Gạo cỏ may 10kg",
  "Bánh snach lay’s đủ",
  "Kẹo Allpenliebe hương dâu",
  "Bánh Choco.Pie",
  "Kẹo cao su lotte",
  "Hủ tiếu nam vang",
  "Mì Omachi xốt bò",
  "Mì hảo hảo xào",
  "Súc xích dinh dưỡng",
  "Hành tím khô",
  "Bột bắp)",
  "Bộ ngủ vị hương",
  "Bột chiên xù",
  "Miến Dong 1",
  "Bánh phồng tôm KLT",
  "Đường Mía Thượng Hạng",
  "Nước tương chin su",
  "Mì Trứng Cao Cấp",
  "Hướng dương vị dừa",
  "Bánh paco đủ vị",
  "Kẹo ngậm Golia",
  "Tảo biển SONKA hàn",
  "Cá Viên , Bò",
  "CHẢ MỰC XOẮN ỐNG",
  "Bánh Bao Nhím",
  "CHẠO TÔM / 1",
  "Bánh Gạo Nhân Pho",
  "Kẹo mút Chupa chup",
  "Bánh thèo lèo",
  "Bánh Goute hạt 316,8g",
  "Bắp bơ Hàn Quốc",
  "Mì hảo hảo chua",
  "NEM CHUA RÁN LĂN",
  "Khoai Tây Chiên",
  "Mực Viên Hàn Quốc",
  "Gạo Mai Tu Hoảnh",
  "Mực bento Thái Lan",
  "Mì trộn khô BBQ",
  "Mì lẩu nấm chua",
  "Miến Phú Hương ăn",
  "Mì ly cung đình",
  "Bánh tráng gạo mè",
  "Xúc xích dinh dưỡng",
  "Pho Mai con bò",
  "Heo 2 lát",
  "COFFEE hoà tan G7",
  "Bột bánh canh khô",
  "Ống dầu vi na",
  "Tỏi Hà Nội",
  "Dầu hào maggi ",
  "Bột ngọt A One",
  "Nước tương maggi đậm",
  "Mayonnaise 260 g",
  "Mì hải sản siu",
  "Phở bò đệ nhất",
  "Mì Đệ Nhất thịt",
  "Miếng phú hương",
  "Nui cao cấp ",
  "Trứng gà tươi",
  "Cá nục sốt cà",
  "Bò 2 lát",
  "Milo Nestle )",
  "Bột mì melzan",
  "Ớt bột",
  "Bột bánh xèo",
  "Bánh trán Đại Lộc",
  "Nước mắm Ông Tây",
  "Nấm mèo Thái Sơn",
  "Bơ thực vật 80g",
  "Muối xí muội hủ",
  "Sốt ớt chanh",
  "Sa tế tôm",
  "Bột gà ri",
  "Mắm Ruốc 170g",
  "Hạt nêm maggi nấm",
  "Giấm Gạo Lên Men",
  "Bột gạo",
  "Rong biển cuộn cơm",
  "Dạo cạo Gillette super",
  "Cầu đá tuyển",
  "Bài 52 cây",
  "Rửa Bình Sữa Dnee",
  "Hạt dưa rang củi",
  "Mì Reeva lẩu nấm",
  "Mì Gấu Đỏ vị",
  "Bánh bao không nhân",
  "Bún riêu cua Vifon",
  "Bánh baonhân chay T.PHAT",
  "Mì Gấu Đỏ tôm",
  "Bánh bao cade T.PHAT",
  "Mi Siukay Ace. vi",
  "Mì OMACHI tôm phomai",
  "Sữa dinh dưỡng Vinamilk",
  "Cream đặc có đường",
  "Thực phẩm Pediasure vani",
  "Thuc uong dd KUN",
  "S-SDN oc cho Vinamilk",
  "Schua uong KUN cam",
  "SChua uong KUN dau",
  "Bánh C'estBON Orion sợi",
  "Bánh gạo Orion tảo",
  "Bánh xốp Richeese Nabati",
  "Bánh quế Cosy Kinh",
  "Bánh snack khoai tây",
  "Bánh C'est BON sợi",
  "Gum Lotte Xylitol hương",
  "Bánh CHOCO-PIE OR.Cacao hg",
  "Bánh AFC dinh dưỡng",
  "Bánh lát khoai tây",
  "Bánh TOK vị bò",
  "Miến Phú Hương thịt",
  "Miến Phú Hương lẩu",
  "Cháo sườn Vifon 70g",
  "Dau gao luc Simply",
  "BNgot AJINOMOTO 1Kg-3005075",
  "Nm N.Ngu nhan vang",
  "Dau an Neptune light",
  "Nm NAMNGU PQUOC tt",
  "Nước tương TAM THÁI",
  "Bngot AJINOMOTO 1.8kg-3229501",
  "Dau an TUONGAN GOLD",
  "Dầu gội Pant siêu",
  "Nước rửa tay Lifebuoy",
  "NX DOWNY huyen bi",
  "Nước tẩy VIM đậm",
  "Khẩu trang vải 3",
  "B.bao t.heo tr.cut CP4cai-320g-3497547",
  "B.hap suatuoi chocolate VQ300g-3001522",
  "X.xich heo Lucky VIS.5c-3352834",
  "Mì xào khô Hảo",
  "Miến đậu xanh yến",
  "Mì A-One vị bò",
  "Mì Miliket vị sate",
  "Mì Hảo Hảo vị",
  "Cháo bổ dưỡng SGF",
  "Phở ChinSu thịt bò",
  "Mì OMACHI lẩu thả",
  "Mì OMACHI Special bò",
  "Creamer đặc Ngôi Sao",
  "Thực phẩm bổ sung",
  "Sữa tươi TH có",
  "Nước uống sữa trái",
  "*S-StuoittVNMOrganic kd4x180ml-3404218",
  "Sữa tiệt trùng Nestle",
  "S-SChua SuSu IQ cd",
  "TPBSA.GOLD Movepro vani ht800g-3409026",
  "TPDD ENSURE Gold vani",
  "Creamer dac NSPN x.bien1.284kg-3413869",
  "S-YomostPoFruit luudau4x170ml-3219350",
  "Phomai VINAMILK 120g-3003258",
  "*STuoi tt VNM it",
  "Bánh crack AFC dd",
  "Bánh Choco-Pie Orion hộp",
  "Bánh gạo Orion tự",
  "Bánh Oreo Kraft soco",
  "Kẹo cafe Kopiko ",
  "Chocola Kitkat 12 thanh",
  "Bánh xốp CAL Cheese",
  "Bánh ăn sáng Kellogg's",
  "Hạnh nhân rang muối",
  "Hạt điều lụa Coop",
  "Bánh TOK Orion vị",
  "Bánh quy COSY Marie",
  "Bánh CHOCO-PIE Orion cacao",
  "Váng sữa Zott Monte",
  "Há cảo tôm CP",
  "Xúc xích CP Vealz",
  "Bún Hằng Nga vị",
  "Nui lớn Safoco 400g",
  "Bánh phở khô Co.op",
  "Miến đậu xanh Co.op",
  "Nước tương NAM DƯƠNG",
  "Sốt MAYONNAISE-MAYO tuýp 130g-3290134",
  "Dau t.vat t.luyen OLITA",
  "BNgot AJINOMOTO 400g-3005077",
  "Tương ớt KNORR 5",
  "Dau dnanh  5L-3269134",
  "Dau an thuc vat",
  "Xxich heo Lucky VIS.10c-3335485",
  "Chan gio heo muoi",
  "Mì trứng cao cấp",
  "Khẩu trang vải kháng",
  "Mì Miliket 2 tôm",
  "Kim chi cải cắt",
  "Mì Cung Đình tôm",
  "Mì trứng th.hang Safoco",
  "Dau dnanh TUONGAN 2L-3003359",
  "Dau an SEASON ccap",
  "Dau dnanh TUONGAN 1L-3003358",
  "Bot ot TAEKYUNG 454g-3360988",
  "Nui khô Safoco đb",
  "Mắm tôm bắc Ngọc",
  "Tàu hũ trứng 300g-3149291",
  "3003641-Bánh qui COSY MARIE",
  "Chocolate SNICKERS 51g-3093975",
  "Bánh crac.M.TWIN 2 lớp",
  "Bánh xốp lúa mạch",
  "Bơ đậu phộng mịn",
  "Bánh xếp MANDU thịt",
  "NGK Coca Light lon",
  "Mì Kokomi 90 tôm",
  "Miến Phú Hương sườn",
  "Hủ tiếu Nhịp Sống",
  "Mì handy Hảo Hảo",
  "Bánh đa cua Hoàng",
  "Xúc xích heo Vissan",
  "Tảo cuộn cơm Shushi",
  "Đường tinh luyện BIÊN",
  "Dầu ăn SIMPLY hạt",
  "Duong mia khoang chat",
  "Nm ca com T.Phat",
  "Duong sach BIEN HOA",
  "Dau dnanh SIMPLY 5L-3003391",
  "Hạt nêm Knorr nấm",
  "Xxich Vealz Super Chef",
  "Xxich Vealz CP 10cay",
  "Cha bo hao hang",
  "Mì trộn khoai tây",
  "Lẩu nấm VN-HQ 600g-3321506",
  "Xà bông Lifebuoy bảo",
  "Khăn tắm Coop Happy",
  "Mì lẩu thái tôm",
  "Mì Udon Suki Suki",
  "Bánh bao thịt theo",
  "Mì Hảo Hảo sườn",
  "Bún gạo Coop Select",
  "Cháo Vifon vị gà",
  "Cháo tươi cá hồi",
  "Sữa Yaourt Long Thành",
  "*Yomost sữa chua trái",
  "Stuoi tt TH it",
  "S-SChua SuSu IQ dauchuoi",
  "S-SChua SuSu IQ taochuoi",
  "Stuoi ttTH it duong",
  "Bánh Choco-Pie Orion 396g",
  "Bánh xốp Nabati rich",
  "Bánh soco Oreo Kraft",
  "Mật ong Viethoney 700ml",
  "Bánh mè giòn GOUTE",
  "Đậu phộng Xuân Hồng",
  "Hạt dinh dưỡng Co.op",
  "Bánh gạo ONE ONE",
  "Xúc xích CP Cocktail",
  "Mì Hảo Hảo tôm",
  "Xúc xích bò Vissan",
  "Xúc xích CP tiệt",
  "Bún tươi Co.op Select",
  "Chà bông heo cao",
  "Lạp xưởng mai quế",
  "Hat nem Maggi nam",
  "Nước tương Chinsu tỏi",
  "Sốt MayonnaiseMAYO ngọt",
  "Hn Chinsu ngottom th.thit",
  "Mì NONGSHIM Chapaghet 140g",
  "BNgot VEDAN 454g-3005080",
  "Dau ca hoi lam",
  "Sốt dầu dấm salad",
  "Dau an TUONGAN 5L-3003388",
  "Nước mắm cá cơm",
  "Sữa chua Vinamilk nếp",
  "Xúc xích hồ lô",
  "Chả giò thịt Vissan",
  "SCU m.song Probi cd",
  "Rau hon hop 5",
  "Sữa chua Vinamilk lựu",
  "Tom vien T.V.SIN-3281533",
  "Sua len men BETA.cam",
  "Lau thai-3001789",
  "Chả lụa quết thượng",
  "Bap My c.dong AGRI",
  "Dau Halan G.Food S.G",
  "Sua len men BETA.dau",
  "Sua len men BETA.pet700ml-3374811",
  "Phomat schua KidsMix Pre",
  "Phomai que DONG DO",
  "Gạo thơm ST24 Co.op",
  "Gạo tấm thơm Xuân",
  "Đậu xanh cà Xuân",
  "Gạo trắng nở xốp",
  "Mi OMACHI tôm phô",
  "Mì KOOL BBQ tô",
  "Mì REEVA 3 Miền",
  "Mì Handy HẢO HẢO",
  "Nước mắm Nam Ngư",
  "Nước tương Maggi đậm",
  "Tương cà Cholimex chai",
  "Bột ngọt Ajinomoto 454g",
  "Đường vàng tự nhiên",
  "Tương đen Cholimex 230g",
  "Nước tương MAGGI đậu",
  "Nước mắm đặc sản",
  "Khăn giấy hộp Coop",
  "Giấy vệ sinh ANAN",
  "Pate gan Hạ Long",
  "Pate heo Vissan có",
  "Heocaoboi th.vien3ph ho-3417223",
  "Ca ngu HALONGndaA)ck175g-3002695",
  "Sữa chua ăn Vinamilk",
  "Cá viên Việt Sin",
  "Sua uong len menYAKULT",
  "Pizza hải sản Lacusina",
  "Co hu dua X.Thu",
  "TPBS Phomai vi sua",
  "Phomaitr.cayLE PETIT PL6-3401930",
  "Đậu đỏ Xuân Hồng",
  "Gạo giống Nhật Co.op",
  "Đường tinh luyện Biên",
  "Bột Ngọt VEDAN 454g",
  "Dầu ăn Happi Koki",
  "Hạt nêmNgon vi",
  "Giấm gạo lên men",
  "Dầu đậu nành ",
  "Dầu TV Coop Select",
  "Dầu olive Olivoilal",
  "Hạt nêmngon heo",
  "Nước Mắm cá cơm",
  "Hạt nêm Neptune 4in1",
  "Khăn ướt baby Coop",
  "Khăn ướt Coop Happy",
  "Cá ngừ ngâm dầu",
  "Pate gan heo Vissan",
  "Sườn heo nấu đậu",
  "Cá nục xốt cà",
  "Mật ong Viethoney chai",
  "Bánh xếp nhân thịt",
  "Xúc xích heo dinh",
  "Há cảo mini Cầu",
  "Cá viên Tân Việt",
  "Bánh bao trứng muối",
  "Chả giò đặc biệt",
  "Phomai L.V.QUIRIT t.thong 224g-3514804",
  "Rau honhop G.Food S.G",
  "Ca trung T.H.HOA-3314363",
  "Sua len men BETA.",
  "SCU m.song Probi v.quat",
  "Thit ba chi bo",
  "Luon ca hoi THH",
  "Gạo thơm thượng hạng",
  "Gạo Nàng Hoa Co.op",
  "Mì CUNG ĐÌNH Kool",
  "Bột canh Vifon 14%",
  "Sa tế tôm Cholimex",
  "Muối tinh sấy Iot",
  "Hạt nêm MAGGI nấm",
  "Bột ngọt Ajinomoto 140g",
  "Đường phèn Coop Select",
  "Muối chanh ớt xanh",
  "Nước Mắm Phú Quốc",
  "Nước mắm Liên Thành",
  "Dầu Cooking Nutri Plus",
  "Giấy vệ sinh E'MOS",
  "Cá sốt cà Co.op",
  "Thịt heo Tulip luncheo",
  "Ca nuc x.ca 3COGAI",
  "NÉSCAFE đậm vị 3in1",
  "Cafe đá 2in1 NAPOLI",
  "Bò viên Tân Việt",
  "Phomai L.V.QUIRIT t.thong 112g-3514803",
  "Sua thtrungDALAT nchat hg950ml-3209004",
  "Sua len men PROBI",
  "Dau hu lua ccap",
  "Khoai tây đông lạnh",
  "Sua len men BETAGENdau4x85ml-3196529",
  "SCU m.song Probi dau",
  "Lau tu xuyen ANVINH",
  "Gạo thơm Jasmine Co.op",
  "Gao lut do XUANHONG",
  "Tương ớt Chinsu chai",
  "Dầu ăn thực vật",
  "Tương ớt Cholimex 270g",
  "Đường kính trắng RS",
  "Dầu hào Maggi 530g",
  "Dấm trộn salad Cholimex",
  "Dầu đậu nành Tường",
  "Dầu ăn Tường An",
  "Khăn ướt Coop Select",
  "Khăn ăn E'mos Prem",
  "Khăn ướt baby Nuna",
  "GVS Coop Select 2lop2Cx5-",
  "Heo 2 lát Hạ",
  "Bò hầm Vissan có",
  "Heo 2 lát Vissan",
  "Cá ngừ trắng Coop",
  "Ngũ cốc dinh dưỡng",
  "Pate 1kg",
  "Cà phê pha sẵn",
  "Bột ăn dặm Túc",
  "Chả bò ớt xiêm",
  "Chả heo1 kg)",
  "Chả bò1 kg)",
  "Pate hộp ",
];

export const drinkKeyWords = [
  "Nước rau má- 1chai",
  "Nước chanh dây Nhà",
  "Nước Rửa Chén 1",
  "Túi Đựng Rác Zise",
  "Nước Ép Carot Chai",
  "Cafe sữa dừa",
  "Sữa Tươi Tiệt Trùng",
  "Nước Dừa Xiêm Chặt",
  "Nước Ép Thơm Chai",
  "Cà Phê hòa Tan",
  "Cà Phê Hòa Tan",
  "Nước Ép Thơm 1",
  "Nước Ép Ổi 1",
  "Nước Mía Chai Nguyên",
  "Nước Suối Aquafina 1,5",
  "Nước Ép Cà Rốt",
  "Mứt Gừng Huế 1/2",
  "Nước Cam Vắt Nguyên",
  "Nước Ép Cần Tây",
  "Nước Ép Cà Chua,",
  "Nước Ổi Ép Nguyên",
  "Nước Dưa Hấu Ép",
  "Nước Thơm Ép Nguyên",
  "Sữa tươi tiệt trùng",
  "Sữa chua ăn có",
  "Sữa uống lên men",
  "Nước Khoáng Gas Đảnh",
  "Aquafina 5l",
  "Cocacola 330ml",
  "Sting Nhân Sâm (Lon)",
  "Jele Thạch L-Carnitine Hương",
  "Jele Thạch Vitamins A.C.E",
  "Mirinda Soda Kem 330ml",
  "Sprite 1.5l",
  "Revive Vị Chanh Muối",
  "Mirinda Xá Xị 330ml",
  "Betagen Hương Cam 700ml",
  "Pepsi 1,5l",
  "7Up 330ml",
  "Betagen Light 700ml",
  "Wake Up 247 (Chai)",
  "Aquafina 0,5l",
  "Lavie 1,5l",
  "Redbull",
  "Revive",
  "Jele Thạch Nước Ép",
  "Ice+ Vị Đào",
  "Jele Thạch L-Glutathione",
  "Schweppes Tonic Water 320ml",
  "Tiger Platinum 330ml",
  "333 Beer",
  "Hillway Trà Sữa Trân",
  "Cafe G7 20 gói*16g",
  "The Coffee House 220g",
  "G7 Cafe Phin Sáng",
  "MacCoffee Capuccino Original 190g",
  "Thiên Việt Yến x6",
  "Yến Thiên Việt Đường",
  "Vnm Sữa Ngôi Sao",
  "VNM Sữa Tươi Có",
  "Vinamilk Sữa Tươi Không",
  "Nutri Boost Strawberry 297ml",
  "Larue Beer",
  "Sài Gòn Beer",
  "Trà sâm dứa Bảo",
  "Nescafe 3in1 Đậm Đà",
  "G7 Lengend Special Edition",
  "Cafe G7 100 gói*16g",
  "TH True Milk 180ml",
  "VNM Sữa Tươi Không",
  "Nuti Milk Sữa Chua",
  "NutiMilk Sữa Chua Có",
  "Lavie 0,5l",
  "Pepsi 330ml",
  "Sting Hương Dâu (Chai",
  "Cocacola Light 330ml",
  "Number One",
  "Milo Protein + Canxi",
  "Fanta Hương Cam 330ml",
  "Schweppes Soda Water 320ml",
  "Nutri Boost Orange 297ml",
  "Cafe Uống Liền Nescafe",
  "Ice+ Vị Cam Chanh",
  "Sprite 330ml",
  "Schweppes Ginger Ale 320ml",
  "Tiger Beer Crystar",
  "Cafe G7 50gói*16g",
  "Trà Gừng Hòa Tan",
  "Cafe Phin Deli 18",
  "Trà Xanh Đặc Sản",
  "G7 Gu Mạnh X2",
  "Yến Thiên Việt Nhân",
  "Vinamilk Ngôi Sao Phương",
  "Or custas kem trứng",
  "Or custas 141g",
  "Oreo strawberry 137g",
  "Lotte toppo Vanilla Strawberry",
  "Lotte toppo vanilla chocolate",
  "Lotte Koala's March Strawberry",
  "Snickers 51g",
  "Aquafina 1,5l",
  "Lavie 6l",
  "Pocari Sweat 500ml",
  "Cocacola Gia Đình 1,5l",
  "Sting Hương Dâu (Lon)",
  "C2 Trà Xanh Hồng",
  "Jele Thạch Double Jelly",
  "Jele Thạch Vitamin C",
  "Trà Xanh 0 Độ",
  "Jele Thạch Blackcurrant",
  "Sting Nhân Sâm (Chai",
  "Tiger Beer",
  "Huda Beer",
  "Vinamilk Ông Thọ 380g",
  "VNM Sữa Tươi Ít",
  "Vinamilk Sữa Tươi Có",
  "Strongbow Redberries 330ml",
  "Heineken Silver Beer",
  "Maccoffe Cafe Phố Đen",
  "Nescafe 3in1 rang xay",
  "Trà Móc Câu Thái",
  "MacCoffe Capuccino Cheese 190g",
  "Yên Thiên Việt x6",
  "Yến Thiên Việt Có",
  "Justnest Nước Yến Thật",
  "Sữa Ông Thọ (Tuýp)",
  "Nước Ép Thạch Táo",
  "Nước Ép Thạch Trái",
  "Trà xanh 100 độ",
  "Sữa MiLo lúa mạch",
  "7up hương chanh 1,5lít",
  "Coca Cola loại chai",
  "Trà lài Mai Vàng",
  "Bia huda",
  "Bia heineken silver 330ml",
  "Sữa vinamil không đường",
  "Sữa đặc có đường",
  "Trà Mật Ong BONCHA",
  "Sữa đặc Rosee",
  "Nước Fmax's (7L) có",
  "Nước khoáng thiên nhiên",
  "Nước Yến lon (",
  "Yến sanest khánh hoà",
  "Sữa đặc ngôi sao",
  "NesCafe 3 -1 (",
  "Cafe Phố Sữa Đá",
  "Trà Gừng hoà tan",
  "Cafe phố sữa đá",
  "Bia tiger",
  "Cocacoca 1,5l",
  "Nước Ép Thạch Dưa",
  "Sữa Tươi Chiên 18",
  "1 Ly Trà Bí",
  "Nước uống AQUAFINA 5",
  "Bò húc Thái",
  "Sting vàng",
  "Nước uống aquafina (",
  "Pepsi 1.5lít",
  "Sprite hương chanh tự",
  "Nước uống Aquoafina chai",
  "Sữa yomost hương dâu",
  "Sữa ngôi sao giấy",
  "Trà sữa trân châu",
  "Nước khoáng thạch bích",
  "Nước Ép Thạch Dâu",
  "Anh đào đông lạnh",
  "Cocacola loại lon",
  "Nước bí đao",
  "Sữa fristi ( lốc",
  "Thức uống dinh dưỡng",
  "Stuoi tt TH ng.chat",
  "S-Ymost schuabha vquat4x170ml-3396912",
  "Trà Nestea vitamin 18",
  "Cà phê đen Nescafe",
  "Cà phê hòa tan",
  "Bia Tiger 24 lon",
  "Nước tinh khiết Aquafina",
  "Nước tăng lực Redbull",
  "Bia HEINEKEN Silver 330ml",
  "Nước ngọt SPRITE pet",
  "Nước tăng lực Sting",
  "Bia 333 330ml -",
  "Bột Milo protein 285g",
  "NGK Pepsi lon cao",
  "NGK Coca khong duong",
  "NGK Mirinda soda kem",
  "Nước khoáng th.nhien Lavie",
  "Cà phê sữa 3in1",
  "Cafe phin so5 T.NGUYEN",
  "Bia HEINEKEN lon cao24x330ml-3372335",
  "Nước ép táo V-Fresh",
  "Nước giải khát Pepsi",
  "Bia Tiger 330ml -",
  "Nước khoáng Vinhhao 1.5L",
  "Ntluc STING dau lon",
  "Nước yến sào ăn",
  "NGK 7up lon cao",
  "NGK Coca plus lon",
  "Yomost sữa chua trái",
  "Sữa đặc Ông Thọ",
  "*S-TPBS Sua lm Milo",
  "Sữa thanh trùng Long",
  "Sữa thanh trùngLong Thành",
  "S-TPBS Grow gold vani",
  "Bot MILO Protomalt hu",
  "Sua dac OngTho chu",
  "S-Sua tuoi tt DLady",
  "TPDD GLUC.TRI.CAREvani ht850g-3281529",
  "SDac ONGTHO chu xanh",
  "TPDD Glucerna vani chai",
  "Cafe sữa Chấtt Vina",
  "Bia LARUE Xanh th",
  "Bia Heineken 0.0 24",
  "S-Bia HEINEKEN lon cao",
  "Nước yến cao cấp",
  "Nước yến sào Sanest",
  "Nước ép đào V-Fresh",
  "Nước giải khát Ice",
  "Sữa chua Vinamilk ít",
  "Sữa chua ăn TH",
  "Trà xanh C2 hương",
  "Nước ngọt Coca-Cola 390ml",
  "Nước uống thể thao",
  "Nước Teppy cam tép",
  "Thức uống dd MILO",
  "Nước uống đóng chai",
  "NGK Mirinda xaxi loncao320ml-3521097",
  "N.t.luc REDBULL thung 24x250ml-3132327",
  "NGK CocaCola lon 320ml-3497147",
  "Giải khát FANTA xá",
  "Bia SAPPORO Premium lốc",
  "Giải khát FANTA soda",
  "MIRINDA xá xị thùng",
  "Kem chống nắng SUNPLAYOGoing",
  "Cà phê sữa hoà",
  "Kem xả Dove phục",
  "Sữa tắm gội Coast",
  "Dầu gội Clear thảo",
  "Wax vuốt tóc ROMANO",
  "Bia HEINEKEN Silver thùng",
  "Bia 333 lốc 6x330ml-3409732",
  "Bia TIGER Crystal lon",
  "Nước táo STRONGBOW Gold",
  "Nước rửa chén Sunlight",
  "Giải khát SPRITE lon",
  "Bia BECK'S Ice lon",
  "MIRINDA xá xị lốc",
  "SPRITE lốc 6x320ml-3501205",
  "Xá xị CHƯƠNG DƯƠNG",
  "Nước ép cam VFRESH",
  "PEPSI lốc pet 6x390ml-3363742",
  "FANTA xá xị thùng",
  "Sữa rửa mặt E100",
  "Sữa rửa mặt Senka",
  "Cafe rang xay Expert",
  "Bia TIGER Crystal thùng",
  "Bia HEINEKEN 0.0 lốc",
  "Bia TIGER lốc 6x330ml-3507531",
  "Nước táo STRONGBOW Dark",
  "Sữa bắp non LOVE'IN",
  "Sữa chua VINAMILK lựu",
  "COCA COLA lon 320ml-3497147",
  "MIRINDA xá xị pet",
  "PEPSI thùng pet 24x390ml-3363741",
  "Bia SAPPORO Premium thùng",
  "7UP thùng pet 24x390ml-3363737",
  "FANTA xá xị lốc",
  "Bia TIGER thùng 24x330ml-3507532",
  "Nước táo STRONGBOW Red",
  "COCA COLA lốc pet",
  "COCA COLA thùng 24x320ml-3497148",
  "7UP lốc pet 6x390ml-3363738",
  "Nước yến ngân nhĩ",
  "Trà LIPTON vàng 50",
  "Cacao hoà tan 6in1",
  "Cà phê hoà tan",
  "Bia HEINEKEN Silver lốc",
  "Nước táo STRONGBOW Honey",
  "Bia 333 thùng 24x330ml-3005028",
  "Bia HEINEKEN 0.0 thùng",
  "Bia BUDWEISER thùng 12x500ml-3398006",
  "Bia TIGER Crystal lốc",
];

export const vegetablesWords = [
  "Nấm Kim Châm",
  "Cải thìa",
  "Tảo biển khô",
  "Hành Tím",
  "Cam",
  "Thơm",
  "Khoai tây",
  "Cà chua",
  "Củ cải",
  "Gừng",
  "Măng vàng",
  "Hành tây",
  "Bắp Xu",
  "Bắp Mĩ",
  "Rau lang",
  "Cổ hũ dừa",
  "Hành Lá",
  "Ớt",
  "Bí hồ lô",
  "Dưa Cải",
  "Cải ngọt",
  "Hành tím",
  "Rau mồng tơi -",
  "Giá Dài Nhỏ",
  "Bún Tươi",
  "Rau Tần Ô( Cải",
  "Rau Diếp Cá",
  "Thơm ( Dứa )",
  "Nấm Đùi Gà 1",
  "Giá Ngắn 1 Gói",
  "Cà Chua Đà Lạt",
  "Dưa Leo 1 Kg",
  "Bí Đỏ Miếng",
  "Bí Ngòi Non 1",
  "Rau Tía Tô",
  "Rau Tần Ô",
  "Củ Cải Trắng",
  "Cải Thảo",
  "Rau Cải Thìa 6",
  "Cà Tím 500gr",
  "Sắn Dây( Củ Đậu)",
  "Khoai Môn Sọ 1/2",
  "Rau Cải Xanh",
  "Rau Cải Con",
  "Quả Quật( Tắc) 1",
  "Nấm Đông Cô 1",
  "Xào Lộn Xộn Cắt",
  "Me Nấu Canh Chua",
  "Củ Dền 1 Phần",
  "Khoai Lang Đà Lạt",
  "Đậu Bắp 1 Phần",
  "Cà Trắng To 1",
  "Đậu hà lan non",
  "Măng Vàng 1 Kg",
  "Môn Sáp Vàng",
  "Cà Chua Bi",
  "Gừng 1 Kg",
  "Chanh dây 1/2 kg",
  "Thơm Gọt Vỏ 1",
  "Hoa Cúc Indo 1",
  "Nấm mèo sạch",
  "Chanh",
  "Măng chua",
  "Bí đao",
  "Boa Rô",
  "Cà tím",
  "Rau má",
  "Sả",
  "Cà rốt",
  "Dưa Leo",
  "Hạt sen",
  "Tỏi",
  "Ớt Đỏ Nhỏ",
  "Đậu ve 1 phần",
  "Mướp hương - 1",
  "Ớt xanh",
  "Dưa Cải Muối Chua",
  "Thơm 1 Miếng",
  "Rau Sống Lộn Xộn",
  "Gừng Quê 1 Lạng",
  "Rau Húng Thơm",
  "Đậu Bắp",
  "Rau ngót - 1",
  "Thơm Cà Lẻ",
  "Rau Quế",
  "Rau Lang Quê",
  "Bắp su - kg",
  "Khoai Tây 1/2 Kg",
  "Bắp Su 1 Phần",
  "Chanh Xanh Quê Lẻ",
  "Cà tím - kg",
  "Chanh Xanh 1/2 Kg",
  "Rau Má",
  "Ớt chuông đỏ -",
  "Ba Rô",
  "Nấm bạch tuyết -",
  "Su su quả",
  "Khổ Qua 1 phânf",
  "Khổ Qua Cắt Sẵn",
  "Củ Cải Trắng kg",
  "Chanh Xanh 1 Kg",
  "Phù Chúc Tươi",
  "Khoai Tây Đà Lạt",
  "Hoa Chuối Cắt Sẵn",
  "Khoai Tây Hà Nội",
  "Dưa Trái Muối 1",
  "Măng Chua Nấu Canh",
  "Rau Lá Lốt",
  "Cà Rốt Mini 1",
  "Cà rốt sạch mini",
  "Dưa Trái Muối",
  "Môn Tàu 1/2 Kg",
  "Bí Đỏ Cắt Sẵn",
  "Khoai Tây Bi",
  "Xà Lách Búp Đà",
  "Đậu Đũa 1 Phần",
  "Măng Vàng 1 Phần",
  "Môn Tàu 1 Kg",
  "Rau dền",
  "Nấm đùi gà",
  "Nấm Tuyết",
  "Củ kịêu chay",
  "Su Su",
  "Dưa Leo - 1",
  "Cà Chua",
  "Trứng gà Bà Mười",
  "Ngò Rí",
  "Mắm Dưa",
  "Bầu Quê 1 Quả",
  "Nấm kim châm -",
  "Hành Tây",
  "Hoa thiên lý -1",
  "Trứng gà ta -",
  "Khổ qua, mướp đắng",
  "Hạt sen Hội An",
  "Nấm Rơm 1 Lạng",
  "Rau cần",
  "Súp lơ trắng -",
  "Rau Dền Xanh Đỏ",
  "Khoai Thập Cẩm",
  "Xà Lách Đà Lạt",
  "Rau Cải Bó Xôi",
  "Cà Rốt Đà Lạt",
  "Rau Răm",
  "Ớt chuông vàng -",
  "Giá Nhỏ 1 Phần",
  "Hành Tây 1 Kg",
  "Lá Giang 1 Phần",
  "Chanh Vàng Sài Gòn",
  "Ớt chuông xanh -",
  "Dưa Hồng 1 Phần",
  "Mì Căn Nướng",
  "Hành Tây+rau Răm 1",
  "Bắp Non 1 Khay",
  "Lá Chanh 1 Phần",
  "Su Su 1 phần",
  "Trầu Cau 1 Dĩa",
  "Rau Xà Lách Sạch",
  "Ớt Chuông Baby 1",
  "Rau Đắng",
  "Lơ Xanh Mini 1",
  "Dưa Món Nhà Làm",
  "Rau Bí 1 Bó",
  "Giá",
  "Chùm tơi",
  "Rau muống",
  "Hành Lá (Thêm)",
  "Cà Rốt Đà Lạt-",
  "Rau muống - 1",
  "Rau Xà Lách Đà",
  "Súp lơ xanh -",
  "Bắp Mỹ 1 Quả",
  "Nấm Bào Ngư 1",
  "Bí Đao Phần",
  "Rau dền xanh đỏ",
  "Măng Cắt Sẵn",
  "Khoai lang giống Nhật",
  "Rau Cải Xanh 1",
  "Rau Cải Ngọt 1",
  "Đậu khuôn 1 miếng",
  "Bí Đỏ Hồ Lô",
  "Nén 1 phần",
  "Ngò Gai",
  "Rau Càng Cua 1",
  "Dưa Leo Bi 1",
  "Cải thảo - kg",
  "Mì Căn Tươi 10",
  "Trứng vịt - 1",
  "Sả 1 Kg",
  "Chuối Chát",
  "Rau Cải Ngọt",
  "Rau Cải Thìa 4",
  "Măng Vàng 1/2 Kg",
  "Thơm Cà Măng Chua",
  "Khoai Sọ 1kg",
  "Bí Đao Cắt Sẵn",
  "Cà Chua Bet 1",
  "Bông bí quả non",
  "Ớt đỏ - 100g",
  "Cải thìa Đà Lạt",
  "Hành Tây 500g",
  "Thơm 1 miếng",
  "Hành Tím 200g",
  "Đậu bắp - 200g",
  "Tỏi Hà Nội 200g",
  "Bắp Mỹ - 1",
  "Đậu Cove Khay 250g",
  "Măng Tây Vietgap Đà",
  "Su Su Đà Lạt",
  "Rong Mứt nấu canh",
  "Ớt chuông Đỏ Vietgap",
  "Hạt ngũ cốc dinh",
  "Bầu gọt sẵn khay",
  "Su Su - Cà",
  "Combo rau sống 300g",
  "Sả Cây 200g",
  "Ngò Rí 100g",
  "Dưa leo Sạch 640g",
  "Rau Muống Nước -",
  "Cà rốt Đất Đà",
  "Bí đao Đà Lạt",
  "Ngò gai Đà Lạt",
  "Rau Diếp Cá 100g",
  "Củ Cải Trắng 1",
  "Rau Lang Đà Lạt",
  "Rau Quế - 50g",
  "Bí Đỏ Tròn Miếng",
  "Nấm Mèo Sạch -",
  "Rau dền Đà Lạt",
  "Khoai Tây 1kg",
  "Hành Tây 1kg",
  "Nấm Mèo thái sợi",
  "Combo canh chua",
  "Rau Ngổ Điếc -50g",
  "Môn Bạc Hà -100g",
  "Combo rau củ sơ",
  "Đậu Cove Xào Sơ",
  "Ớt Chuông Xào Hành",
  "Combo Củ Quả Cắt",
  "Nấm Kim Châm Gói",
  "Giá Đỗ -250g",
  "Nấm Đùi Gà Non",
  "Rau mồng tơi Đà",
  "Mướp hương quả ~",
  "Cà Tím quả ~",
  "Khổ qua Đà Lạt",
  "Chanh Tươi - 0.5Kg",
  "Cải xanh Đà Lạt",
  "Tía tô 100g",
  "Húng Thơm - 50g",
  "Nghệ tươi - 100g",
  "Ớt Xanh Huế _",
  "Dưa Cải Chua _",
  "Măng Chua-100g",
  "Rong Biển Ăn Liền",
  "Đậu Khuôn _4 Miếng",
  "Nấm linh chi gói",
  "Ớt chuông Vàng Vietgap",
  "Chanh không hạt Đà",
  "Cà chua Đà Lạt",
  "Gừng Ta 100g",
  "Khoai Tây 0.5kg",
  "Bầu 1 Quả 710g",
  "Cải thảo Đà Lạt",
  "Thơm 1 Quả",
  "Súp lơ xanh Đà",
  "Rau Tần Ô Bó",
  "Lá lốt 100g",
  "Rau má 250g",
  "Ớt chuông Xanh Vietgap",
  "Nấm Đông Cô Khô",
  "Đu đủ sống_500g",
  "Cải ngọt Đà Lạt",
];

export const fruitWords = [
  "Xoài nha trang sống-",
  "Xoài keo Vàng -",
  "Thanh long Trắng Hơn",
  "Xoài Keo Xanh 1",
  "Hoa Cúc Lưới lớn",
  "Nho xanh ko hạt-",
  "Mận đá - kg",
  "Dưa Hấu Ko Hạt",
  "Xoài Cát Hòa Lộc",
  "Chuối mốc chín",
  "Bơ 034",
  "Xoài nha trang chín",
  "Nhãn 1/2 Kg",
  "Dưa Lưới Dài Vàng",
  "Nước Lau Sàn Sunlight",
  "Nước Ép Cà Chua",
  "Sữa Đặc Ông Thọ",
  "Táo đỏ",
  "Ổi có hạt -",
  "Chanh dây - kg",
  "Táo ta - kg",
  "Dừa xiêm - 1",
  "Cóc (loại to) -",
  "Thanh long ruột Đỏ",
  "Dưa Hấu Có Hạt",
  "Cam vietgap-1kg",
  "Đu đủ - 2kg",
  "Quýt úc",
  "Dưa Hấu Dài 1",
  "Cúc Indo Màu Đồng",
  "Bưởi hồng da xanh",
  "Táo Mỹ Bree 1",
  "Cam Úc Navel 1",
  "Chuối",
  "Cam sành - 1kg",
  "Xoài Tứ Quý",
  "Hồng xiêm -1kg",
  "Quýt Úc 1/2 Kg",
  "Lê Hàn quốc 1",
  "Hoa Cúc Lưới Nhỏ",
  "Me Thái 1/2 Kg",
  "Bơ sáp 1 phần",
  "Bơ tuýp 100g",
  "Táo đen",
  "Ổi Nữ Hoàng Ko",
  "Dưa hấu không hạt",
  "Dâu tây - 1",
  "Mận - kg",
  "Nhãn -1kg",
  "Măng cụt - kg",
  "Mận 1/2 Kg",
  "Chôm chôm Thái -",
  "Táo rockit- 1 ống",
  "Táo Mỹ envy to",
  "Cam vàng-1kg",
  "Me Thái 1kg",
  "Bưởi Lột Sẳn _",
  "Bánh hạt dinh dưỡng",
  "Combo khoai lang cà",
  "Set rau ăn nướng",
  "Combo Nướng Hoàn Chỉnh",
  "Combo bò xào lá",
  "Combo bò xào ớt",
  "Canh đu đủ và",
  "Combo bò xào khổ",
  "Ổi Cắt Sẵn _400g",
  "Dừa Xiêm Size 1",
  "Combo 3 Trái Bưởi",
  "Vải U Hồng -1kg",
  "Bưởi da xanh size",
  "Xoài Cắt Sẵn _400g",
  "Combo Bưởi -Ổi- Táo",
  "Combo Xoài - Ổi",
  "Combo Ổi - Xoài",
  "Dưa hấu 1 quả",
  "Mận An Phước -",
  "Xoài Keo - 1kg",
  "Ổi Nữ Hoàng -1kg",
  "Cóc non -500g",
  "Đu Đủ - 1,14kg",
  "Mít Thái Lột Sẵn",
  "Dưa Hấu Cắt Sẵn",
  "Mận Hậu ~ Hộp",
  "Mít Thái Cắt Sẵn",
  "Quýt Úc size lớn",
  "Combo Dừa xiêm gọt",
  "Bơ Sáp -1kg",
  "Đu Đủ Cắt Sẵn",
  "Combo Cóc - Xoài",
  "Combo Thơm-Xoài-Ổi cắt sẵn",
  "Combo Dưa hấu-Táo- Thanh",
  "Nhãn Thái _500g",
  "Combo Dừa Xiêm Gọt",
  "Dâu đông lạnh",
  "Combo 2 túi Dâu",
  "Trái mọng đỏ tổng",
  "Việt quất puree xay",
  "Việt quất đông lạnh",
  "Hồ Lô Loại 1",
  "Nhồi Sụn Loại Hảo",
];
